/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClientControl;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Message;
import model.Player;

/**
 *
 * @author hieudx
 */
public class PlayerHomeView extends javax.swing.JFrame implements ActionListener {

    private Player player;
    private List<Player> listPlayer;
    DefaultTableModel tm;

    /**
     * Creates new form PlayerHomeView
     */
    public PlayerHomeView() {
        initComponents();
    }

    public PlayerHomeView(Player player, List<Player> listPlayer) {
        initComponents();
        String[] cols = {"Username", "Point"};
        tm = new DefaultTableModel(cols, 0);
        tblOnline.setModel(tm);
        this.setLocation(500, 200);
        this.player = player;
        this.listPlayer = listPlayer;
        lbUsername.setText(player.getUsername());
        loadListPlayer();
    }

    public void loadListPlayer() {
        tm.setRowCount(0);
        for (Player p : listPlayer) {
            if (p.getId() != player.getId()) {
                tm.addRow(p.toObject());
            }
        }
    }

    public Player getPlayerToInvite() {
        Player player = null;
        int row = tblOnline.getSelectedRow();
        if (row < 0 || row > tm.getRowCount()) {
            showMessage("Select a player to invite");
            return null;
        } else {
            String username = tblOnline.getValueAt(row, 0).toString();
            for (Player p : listPlayer) {
                if (p.getUsername().equalsIgnoreCase(username)) {
                    player = p;
                }
            }
        }
        return player;

    }

    @Override
    public void actionPerformed(ActionEvent e) {

    }

    public void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    
    public boolean showConfirmDialog(Player p) {
        int x = JOptionPane.showConfirmDialog(this, p.getUsername() + " invite you to play");
        if (x == JOptionPane.YES_OPTION) {
            return true;
        }
        return false;
    }

    public void addActionListener(ActionListener log) {
        btnInvite.addActionListener(log);
        btnEnterRoom.addActionListener(log);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOnline = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnInvite = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnRefreshRoom = new javax.swing.JButton();
        btnEnterRoom = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbUsername = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("3Que");

        tblOnline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOnline);

        jLabel2.setText("Danh sách Online");

        btnInvite.setText("Mời");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel3.setText("Danh sách bàn");

        btnRefreshRoom.setText("Làm mới bàn");

        btnEnterRoom.setText("Vào bàn");

        jLabel4.setText("Welcome");

        lbUsername.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnRefreshRoom)
                .addGap(18, 18, 18)
                .addComponent(btnEnterRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInvite)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lbUsername)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lbUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInvite)
                    .addComponent(btnRefreshRoom)
                    .addComponent(btnEnterRoom))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Player getPlayer() {
        return player;
    }

    public void setPlayer(Player player) {
        this.player = player;
    }

    public List<Player> getListPlayer() {
        return listPlayer;
    }

    public void setListPlayer(List<Player> listPlayer) {
        this.listPlayer = listPlayer;
    }

    public JButton getBtnEnterRoom() {
        return btnEnterRoom;
    }

    public void setBtnEnterRoom(JButton btnEnterRoom) {
        this.btnEnterRoom = btnEnterRoom;
    }

    public JButton getBtnInvite() {
        return btnInvite;
    }

    public void setBtnInvite(JButton btnInvite) {
        this.btnInvite = btnInvite;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterRoom;
    private javax.swing.JButton btnInvite;
    private javax.swing.JButton btnRefreshRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JTable tblOnline;
    // End of variables declaration//GEN-END:variables

}
